### ISSUE TITLE
Support 1.20.2 and potential support for 1.21

### ISSUE THREAD

**Issue by Qubik65536** [gbl/Beenfo#36]
Hi @gbl,

Can you release a version for 1.20.2 (no release on Modrinth have been labeled as 1.20.2 supported)?
And is there a plan for supporting 1.21+?

Thanks,

**Comment by sternschnaube** [comment]
Tested it right now (Client+Server) on Fabric (Loader 0.15.0) 1.20.2, no problems.
@Cubik65536 @gbl 

Can be marked as 1.20.2 compatible.

**Comment by Qubik65536** [comment]
> Tested it right now (Client+Server) on Fabric (Loader 0.15.0) 1.20.2, no problems. @Cubik65536 @gbl
> 
> Can be marked as 1.20.2 compatible.

Thanks!

**Comment by sternschnaube** [comment]
Hello @Cubik65536 and @gbl, I need to apologize.

Mod loads fine on Client and Server. Hovering over the Bee Hive was working with the HUD as well, but created this error in the server log:

Error executing task on Server
java.lang.IllegalArgumentException: Cannot get property class_2758{name=honey_level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5]} as it does not exist in Block{minecraft:air}
	at net.minecraft.class_2688.method_11654(class_2688.java:98) ~[server-intermediary.jar:?]
	at de.guntram.mcmod.beenfo.BeenfoServer.sendHudContent(BeenfoServer.java:90) ~[beenfo-1.20-fabric0.83.0-1.3.3-spigot.jar:?]
	at de.guntram.mcmod.beenfo.BeenfoServer.lambda$processClientPacket$1(BeenfoServer.java:84) ~[beenfo-1.20-fabric0.83.0-1.3.3-spigot.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.mixinextras$bridge$method_18859$5(class_4093.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.wrapOperation$cmf000$carpet-tis-addition$yeetUpdateSuppressionCrash_implForThreadExecutorTaskExecuting(class_4093.java:552) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:778) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:163) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:760) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:754) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:738) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zjo000$carpet$modifiedRunLoop(MinecraftServer.java:19960) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:28:41] [Server thread/ERROR]: Error executing task on Server

**Comment by sternschnaube** [comment]
On the client side, while trying to open the GUI, this crash occurs:

Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:955)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'void de.guntram.mcmod.beenfo.BeenfoScreen.method_25420(net.minecraft.class_332)'
	at de.guntram.mcmod.beenfo.BeenfoScreen.method_25394(BeenfoScreen.java:56)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:946)
	... 6 more

**Comment by Qubik65536** [comment]
@sternschnaube 
Yeah... I also tried to port it to 1.20.2+, didn't work, now I'm just using some alternatives.

**Comment by sternschnaube** [comment]
That's good, Beehave is a great alternative.

**Comment by Qubik65536** [comment]
> That's good, Beehave is a great alternative.

Yeah I'm just using Jade to see the info without having to click on it.

**Comment by sternschnaube** [comment]
I'm on the WTHIT side 😄
It's one of the simplest solutions.

But I like to have a openable GUI from Beenfo in the future again 😊

**Comment by gbl** [comment]
Just put a 1.20.4 version up, which will probably work on 1.20.3 as well.

**Comment by sternschnaube** [comment]
Thanks!!
